echo -e '\e[40m\e[92m'
echo -e '                                              |    '
echo -e '                                              |    '
echo -e '                                              |    '
echo -e '                                              |    '
echo -e '        .-------------------.                 |    '
echo -e '        |  Hi, FOMOfucker!  |                 |    '
echo -e '        `-------------------`                 |    '
echo -e '                  ^         (\\_/)             |    '
echo -e '                   `------- (O.o)             |    '
echo -e '                            (> <)             |    '
echo -e '                         ====^=^==============|    '
echo -e '                                              |    '
echo -e '                                              |    '
echo -e '                                              |    '
echo -e '                                              |    '
echo -e '                                              |    '
echo -e '                                              |    '
echo -e '                                              |    '
echo -e '                                              |    '
echo -e '\e[0m'
